### ISSUE TITLE
Include cpd-cli within the deployer image

### ISSUE THREAD

**Issue by pgirishibm** [IBM/cloud-pak-deployer#159]
**Is your feature request related to a problem? Please describe.**
I need to run cpd-cli odap command  from within the deployer image. 

**Describe the solution you'd like**
currently cpd-cli is not included in the deployer image. Adding it would definitely help with how the deployer is extended further for other requriements. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by fketelaars** [comment]
@pgirishibm I have updated the code so that cpd-cli is downloaded in the first phases of the apply process. It is not really practical to include cpd-cli in the deployer `image` because not all Cloud Paks need it. To force download, you can do the following:
* Ensure the STATUS_DIR and CONFIG_DIR environment variables are set
* Run the following command:
```
cp-deploy.sh env download --skip-mirror-images
```

It should be possible to run this from within the container.
