### ISSUE TITLE
Ability to mirror all components for an air gapped install

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#575]
When performing an air gapped install the deployer will only mirror the images for the selected components in the config yaml.

The problem is that for some customer deployments you might choose to only deploy some components initially and then re run the deployer to add further components.  One example being a phased rollout or in a PoC where the customer expresses an interest in another capability and there is a new sales opportunity.  Adding WKC for example.

Currently the only way to mirror all available images is to create a new config yaml with everything set to installed purely to use with cp-deploy.sh env download.  

It would be great if there was a --mirror-all flag and this could also include --arch=amd64 to only mirror the required architecture (where this is supported).

**Comment by fketelaars** [comment]
In most situations, you will only want to mirror the images applicable to the installation you're doing. Mirroring the images for all services included in CP4D, including watsonx, will accumulate to many GBs.

If you really want to mirror the images, even of most of them remain unused, you can do the following:
- Change the state of all cartridges to `installed`
- Run deployer with `env download` action

This will then download all images to the portable registry.

Once on-site to do the install, mirror the images to the customer's private registry and change the deployer's cp4d configuration so that only the services the customer wants to deployer are installed.
