### ISSUE TITLE
Allow running Deployer on Power

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#591]
In CP4D 4.8, broader support for Power is available. Allow deployer to run on Power.

**Comment by schabrolles** [comment]
Hi Frank,

If I could help on this, don't hesitate.
I quickly try to rebuild the container, but some product seems to be hardcoded to x86.
helm and some other are available on ppc64le, but I have some difficulties with openjdk-9.

Can we use openjdk-8 or other version (11,17,21) which are supported and can be easily setup with yum/dnf ?

**Comment by fketelaars** [comment]
Hi @schabrolles I made some initial changes to remove the Dockerfile x86 dependencies. Java and helm are only needed for CP4BA, hence deployer now only installs them if CP4BA is seelcted. Additionally I have removed olm-utils (v1) image from the Dockerfile as there is no Power version of it.

I would appreciate if you can test the changes in the `deployer-power` branch on your cluster.

**Comment by schabrolles** [comment]
Hi @fketelaars 

I make it work after some cleaning anf changes:

1. in the Dockerfile:
  - Use a non-official valut port for Power (hashicorp doesn't provide them)
  - Add gcc and python devel to rebuild missing python dependencies during `pip install`
  - Workaround to build wheel due to some cython and PyYaml issues 

2. Fixing some hardcoded x86 binary download in shell script and Ansible
  - Create an `ARCH` variable (using `uname -m`) in order to automatically set the right arch when downloading files.
  
a container image is available here: quay.io/schabrolles/cloud-pak-deployer:latest

I've already tested it to deploy CP4D 4.8.3 with DB2 OLTP on Power, but we should share it with others for further testing.

**Comment by fketelaars** [comment]
Thanks @schabrolles , that is great news! Will pull in other resources who can test as well.
