### ISSUE TITLE
Container image cloud-pak-deployer does not exist on the local machine, please build first.

### ISSUE THREAD

**Issue by marcdecker** [IBM/cloud-pak-deployer#63]
**Describe the bug**
During cp-deploy.sh vault set on an airgapped bastion, the following error occurs:
Container image cloud-pak-deployer does not exist on the local machine, please build first.

**To Reproduce**
1. Go to dir where cp-deploy.sh is
2. Run e.g.

./cp-deploy.sh vault set \
  -vs defense-oc-login \
  -vsv "oc login api.ocp48.tec.uk.ibm.com:6443 -u ocadmin -p passw0rd --insecure-skip-tls-verify"

3. 

**Expected behavior**
I expect an entry to be added in the vault

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Red Hat Linux

**Smartphone (please complete the following information):**

**Additional context**
Solved by first running

./cp-deploy.sh env apply \
    -e env_id=defense \
    --air-gapped

afterwards running the vault command again

**Comment by fketelaars** [comment]
Changes to be made:
- [ ] Make `image_registry_name` mandatory for `cp4d` when air-gapped
- [ ] Document `image_registry` and `cp4d` configuration as part of air-gapped steps
- [ ] Use CPD_AIRGAP environment variable instead of `--air-gapped` flag
- [ ] Set `registry-storage` directory regardless of original value

**Comment by fketelaars** [comment]
Fixed and merged.
